name: First Workflow
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - Bye!"
      - name: Run multi-line Shell Command
        run: |
          echo "command 1"
          echo "command 2"
